from itertools import product
from multiprocessing import Pool
from experiment import run_experiment

# this script uses parallelization

config_dicts = [
    {
        "network_family": 'lattice',
        "nodes": 2000,
        "edges": 10,
    },
    {
        "network_family": 'erdosrenyi',
        "nodes": 2000,
        "edges": 10,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 2000,
        "edges": 10,
        "p": 0.0,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 2000,
        "edges": 10,
        "p": 0.1,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 2000,
        "edges": 10,
        "p": 0.2,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 2000,
        "edges": 10,
        "p": 0.3,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 2000,
        "edges": 10,
        "p": 0.4,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 2000,
        "edges": 10,
        "p": 0.5,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 2000,
        "edges": 10,
        "p": 0.6,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 2000,
        "edges": 10,
        "p": 0.7,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 2000,
        "edges": 10,
        "p": 0.8,
    },
    {
        "network_family": 'smallworld',
        "nodes": 2000,
        "edges": 10,
        "p": 0.0,
    },
    {
        "network_family": 'smallworld',
        "nodes": 2000,
        "edges": 10,
        "p": 0.1,
    },
    {
        "network_family": 'smallworld',
        "nodes": 2000,
        "edges": 10,
        "p": 0.2,
    },
    {
        "network_family": 'smallworld',
        "nodes": 2000,
        "edges": 10,
        "p": 0.3,
    },
    {
        "network_family": 'smallworld',
        "nodes": 2000,
        "edges": 10,
        "p": 0.4,
    },
    {
        "network_family": 'smallworld',
        "nodes": 2000,
        "edges": 10,
        "p": 0.5,
    },
    {
        "network_family": 'smallworld',
        "nodes": 2000,
        "edges": 10,
        "p": 0.6,
    },
    {
        "network_family": 'smallworld',
        "nodes": 2000,
        "edges": 10,
        "p": 0.7,
    },
    {
        "network_family": 'smallworld',
        "nodes": 2000,
        "edges": 10,
        "p": 0.8,
    },
    {
        "network_family": 'lattice',
        "nodes": 500,
        "edges": 10,
    },
    {
        "network_family": 'erdosrenyi',
        "nodes": 500,
        "edges": 10,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 500,
        "edges": 10,
        "p": 0.0,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 500,
        "edges": 10,
        "p": 0.1,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 500,
        "edges": 10,
        "p": 0.2,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 500,
        "edges": 10,
        "p": 0.3,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 500,
        "edges": 10,
        "p": 0.4,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 500,
        "edges": 10,
        "p": 0.5,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 500,
        "edges": 10,
        "p": 0.6,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 500,
        "edges": 10,
        "p": 0.7,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 500,
        "edges": 10,
        "p": 0.8,
    },
    {
        "network_family": 'smallworld',
        "nodes": 500,
        "edges": 10,
        "p": 0.0,
    },
    {
        "network_family": 'smallworld',
        "nodes": 500,
        "edges": 10,
        "p": 0.1,
    },
    {
        "network_family": 'smallworld',
        "nodes": 500,
        "edges": 10,
        "p": 0.2,
    },
    {
        "network_family": 'smallworld',
        "nodes": 500,
        "edges": 10,
        "p": 0.3,
    },
    {
        "network_family": 'smallworld',
        "nodes": 500,
        "edges": 10,
        "p": 0.4,
    },
    {
        "network_family": 'smallworld',
        "nodes": 500,
        "edges": 10,
        "p": 0.5,
    },
    {
        "network_family": 'smallworld',
        "nodes": 500,
        "edges": 10,
        "p": 0.6,
    },
    {
        "network_family": 'smallworld',
        "nodes": 500,
        "edges": 10,
        "p": 0.7,
    },
    {
        "network_family": 'smallworld',
        "nodes": 500,
        "edges": 10,
        "p": 0.8,
    },
    {
        "network_family": 'lattice',
        "nodes": 1000,
        "edges": 10,
    },
    {
        "network_family": 'erdosrenyi',
        "nodes": 1000,
        "edges": 10,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 1000,
        "edges": 10,
        "p": 0.0,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 1000,
        "edges": 10,
        "p": 0.1,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 1000,
        "edges": 10,
        "p": 0.2,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 1000,
        "edges": 10,
        "p": 0.3,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 1000,
        "edges": 10,
        "p": 0.4,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 1000,
        "edges": 10,
        "p": 0.5,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 1000,
        "edges": 10,
        "p": 0.6,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 1000,
        "edges": 10,
        "p": 0.7,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 1000,
        "edges": 10,
        "p": 0.8,
    },
    {
        "network_family": 'smallworld',
        "nodes": 1000,
        "edges": 10,
        "p": 0.0,
    },
    {
        "network_family": 'smallworld',
        "nodes": 1000,
        "edges": 10,
        "p": 0.1,
    },
    {
        "network_family": 'smallworld',
        "nodes": 1000,
        "edges": 10,
        "p": 0.2,
    },
    {
        "network_family": 'smallworld',
        "nodes": 1000,
        "edges": 10,
        "p": 0.3,
    },
    {
        "network_family": 'smallworld',
        "nodes": 1000,
        "edges": 10,
        "p": 0.4,
    },
    {
        "network_family": 'smallworld',
        "nodes": 1000,
        "edges": 10,
        "p": 0.5,
    },
    {
        "network_family": 'smallworld',
        "nodes": 1000,
        "edges": 10,
        "p": 0.6,
    },
    {
        "network_family": 'smallworld',
        "nodes": 1000,
        "edges": 10,
        "p": 0.7,
    },
    {
        "network_family": 'smallworld',
        "nodes": 1000,
        "edges": 10,
        "p": 0.8,
    },
    {
        "network_family": 'lattice',
        "nodes": 2000,
        "edges": 20,
    },
    {
        "network_family": 'erdosrenyi',
        "nodes": 2000,
        "edges": 20,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 2000,
        "edges": 20,
        "p": 0.0,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 2000,
        "edges": 20,
        "p": 0.1,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 2000,
        "edges": 20,
        "p": 0.2,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 2000,
        "edges": 20,
        "p": 0.3,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 2000,
        "edges": 20,
        "p": 0.4,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 2000,
        "edges": 20,
        "p": 0.5,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 2000,
        "edges": 20,
        "p": 0.6,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 2000,
        "edges": 20,
        "p": 0.7,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 2000,
        "edges": 20,
        "p": 0.8,
    },
    {
        "network_family": 'smallworld',
        "nodes": 2000,
        "edges": 20,
        "p": 0.0,
    },
    {
        "network_family": 'smallworld',
        "nodes": 2000,
        "edges": 20,
        "p": 0.1,
    },
    {
        "network_family": 'smallworld',
        "nodes": 2000,
        "edges": 20,
        "p": 0.2,
    },
    {
        "network_family": 'smallworld',
        "nodes": 2000,
        "edges": 20,
        "p": 0.3,
    },
    {
        "network_family": 'smallworld',
        "nodes": 2000,
        "edges": 20,
        "p": 0.4,
    },
    {
        "network_family": 'smallworld',
        "nodes": 2000,
        "edges": 20,
        "p": 0.5,
    },
    {
        "network_family": 'smallworld',
        "nodes": 2000,
        "edges": 20,
        "p": 0.6,
    },
    {
        "network_family": 'smallworld',
        "nodes": 2000,
        "edges": 20,
        "p": 0.7,
    },
    {
        "network_family": 'smallworld',
        "nodes": 2000,
        "edges": 20,
        "p": 0.8,
    },
    {
        "network_family": 'lattice',
        "nodes": 500,
        "edges": 20,
    },
    {
        "network_family": 'erdosrenyi',
        "nodes": 500,
        "edges": 20,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 500,
        "edges": 20,
        "p": 0.0,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 500,
        "edges": 20,
        "p": 0.1,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 500,
        "edges": 20,
        "p": 0.2,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 500,
        "edges": 20,
        "p": 0.3,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 500,
        "edges": 20,
        "p": 0.4,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 500,
        "edges": 20,
        "p": 0.5,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 500,
        "edges": 20,
        "p": 0.6,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 500,
        "edges": 20,
        "p": 0.7,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 500,
        "edges": 20,
        "p": 0.8,
    },
    {
        "network_family": 'smallworld',
        "nodes": 500,
        "edges": 20,
        "p": 0.0,
    },
    {
        "network_family": 'smallworld',
        "nodes": 500,
        "edges": 20,
        "p": 0.1,
    },
    {
        "network_family": 'smallworld',
        "nodes": 500,
        "edges": 20,
        "p": 0.2,
    },
    {
        "network_family": 'smallworld',
        "nodes": 500,
        "edges": 20,
        "p": 0.3,
    },
    {
        "network_family": 'smallworld',
        "nodes": 500,
        "edges": 20,
        "p": 0.4,
    },
    {
        "network_family": 'smallworld',
        "nodes": 500,
        "edges": 20,
        "p": 0.5,
    },
    {
        "network_family": 'smallworld',
        "nodes": 500,
        "edges": 20,
        "p": 0.6,
    },
    {
        "network_family": 'smallworld',
        "nodes": 500,
        "edges": 20,
        "p": 0.7,
    },
    {
        "network_family": 'smallworld',
        "nodes": 500,
        "edges": 20,
        "p": 0.8,
    },
    {
        "network_family": 'lattice',
        "nodes": 1000,
        "edges": 20,
    },
    {
        "network_family": 'erdosrenyi',
        "nodes": 1000,
        "edges": 20,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 1000,
        "edges": 20,
        "p": 0.0,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 1000,
        "edges": 20,
        "p": 0.1,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 1000,
        "edges": 20,
        "p": 0.2,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 1000,
        "edges": 20,
        "p": 0.3,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 1000,
        "edges": 20,
        "p": 0.4,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 1000,
        "edges": 20,
        "p": 0.5,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 1000,
        "edges": 20,
        "p": 0.6,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 1000,
        "edges": 20,
        "p": 0.7,
    },
    {
        "network_family": 'powerlaw',
        "nodes": 1000,
        "edges": 20,
        "p": 0.8,
    },
    {
        "network_family": 'smallworld',
        "nodes": 1000,
        "edges": 20,
        "p": 0.0,
    },
    {
        "network_family": 'smallworld',
        "nodes": 1000,
        "edges": 20,
        "p": 0.1,
    },
    {
        "network_family": 'smallworld',
        "nodes": 1000,
        "edges": 20,
        "p": 0.2,
    },
    {
        "network_family": 'smallworld',
        "nodes": 1000,
        "edges": 20,
        "p": 0.3,
    },
    {
        "network_family": 'smallworld',
        "nodes": 1000,
        "edges": 20,
        "p": 0.4,
    },
    {
        "network_family": 'smallworld',
        "nodes": 1000,
        "edges": 20,
        "p": 0.5,
    },
    {
        "network_family": 'smallworld',
        "nodes": 1000,
        "edges": 20,
        "p": 0.6,
    },
    {
        "network_family": 'smallworld',
        "nodes": 1000,
        "edges": 20,
        "p": 0.7,
    },
    {
        "network_family": 'smallworld',
        "nodes": 1000,
        "edges": 20,
        "p": 0.8,
    },
]

with Pool(20) as p:
    p.starmap(run_experiment, product(config_dicts, range(30)))

# run_experiment(config_dict, 1)
